// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kelmxkyefqgltwovicoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlbG14a3llZnFnbHR3b3ZpY295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODk1OTUsImV4cCI6MjA1OTM2NTU5NX0.PnMZ4bTt7Q407CcaviAtdJlWfLAXwqowCwomIG1M2Bc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);